### ISSUE TITLE
Cannot open video in Huawei M10 HarmonyOS

### ISSUE THREAD

**Issue by HQYang1979** [lrorpilla/jidoujisho#151] opened 2023-02-02 06:21 UTC
Cannot open video in Huawei M10 HarmonyOS, nothing shows up. Will you improve it?

**Comment by HQYang1979** [comment] 2023-02-02 06:26
And thank you very much for this app, I can look up Spanish too, space delimited languages

**Comment by lrorpilla** [comment] 2023-03-11 18:04
Can you give me more details on this issue? A video showing the issue would be helpful. I can probably offer an alternative file picker for users having issues.

In the meantime, the alternative I suggest is hosting your videos on your PC via Jellyfin then using the Jellyfin Android app as an external player.

**Comment by lrorpilla** [comment] 2023-04-11 03:41
@HQYang1979, sorry to follow up but are you still available to give debug information? It seems HarmonyOS devices have unique manufacturer-specific issues with file picking: https://github.com/ppy/osu/issues/11911.

**Comment by HQYang1979** [comment] 2023-04-14 00:39
Irorpilla, the issue still persists in my Huawei device, actually there is no any error message, local video just cannot open without any error message.

**Comment by lrorpilla** [comment] 2023-04-14 01:37
@HQYang1979 Does the file become added to your Player tab? If so, can you send a screenshot of the Player tab?

**Comment by lrorpilla** [comment] 2023-04-14 02:15
Could you also please confirm if you have granted all files permission on your device? I can't find any error logs for your device model.

**Comment by NoHeartPen** [comment] 2023-04-22 13:06
Perhaps placing the files to be opened in the 'Documents' folder of the root directory (or a folder commonly found in systems such as' Download') can solve this problem? The products developed by Chinese developers seem to have no such requirements, so as a Chinese college student majoring in Japanese, I initially encountered similar problems (my phone system is based on MIUI 14 on Android 12, and I also encountered the same problem on a Color OS based on Android 7 and solved it through the same method).

![1682165559773](https://user-images.githubusercontent.com/79316356/233786949-a3bfcff7-2b9a-4ea3-ac3a-5a869461d6d5.jpg)

![1682165559764](https://user-images.githubusercontent.com/79316356/233786955-d6bc56d1-e0af-4eb5-b42b-9abc51e512f3.jpg)

**Comment by lrorpilla** [comment] 2023-04-30 03:44
@NoHeartPen Would you say this is a manufacturer-specific issue to the extent that other apps have it or would you say this is something that I need to fix?

I have tried this app on a lot of phones but I still don't have a ColorOS phone I can test with unfortunately. I'm thinking of closing this issue if this is out of my control an is due to certain manufacturers just being weird with file picking.

**Comment by NoHeartPen** [comment] 2023-05-06 13:56
I think this is a manufacturer-specific issue, so I suggest you write a tip like this: 
> If you can't  open the video correctly, you can make the file into the path named 'Download' or 'Document' 
>如果你不能打开视频，可以考虑把文件放到根目录下的`Download`或`Document`文件夹

This issue may be caused by China smartphone manufacturer made some problems with system permissions, so Chinese may be more helpful:)

**Comment by lrorpilla** [comment] 2023-05-07 05:46
I've decided to close this issue. Users can refer to [**this section**](https://github.com/lrorpilla/jidoujisho/wiki/2.-Troubleshooting#i-cant-pick-files-or-cant-view-media-after-picking-them) in the wiki if they're still having issues.

**Closed by lrorpilla** 2023-05-07 05:46 UTC
Labels: bug
