### ISSUE TITLE
Plex support?

### ISSUE THREAD

**Issue by Lyhcan** [lrorpilla/jidoujisho#245] opened 2023-06-05 23:36 UTC
First things first i wanna thank you for this amazing app it has been a game changer for my english learning.

Could you add support for Plex so it saves the progress when i close/minimize the jidoujisho app? currently i can use jidoujisho as an external player for the plex app so when i click to watch a movie on the plex app it automatically opens on jidoujisho, the problem is that if i minimize or close jidoujisho while watching it resets/does not save the media progress. for example, i was watching a movie and was almost finishing it, i minimized the app to check whatsapp quickly and when i returned to the app the movie progress was reset, i had to open the movie again and find the exact time i stopped

**Comment by lrorpilla** [comment] 2023-06-06 00:39
Plex doesn't pass subtitle information to the app. Their external player support is inferior to Jellyfin's, and they have no progress tracking. That's why I promote the latter over the other. 

The app closing upon minimize is intended behavior as the app acts in a very particular way when acting as an external player.

Plex users won't get development support from this app, but if you use Jellyfin and have a problem, I will look at it.

**Closed by lrorpilla** 2023-06-06 00:39 UTC
Labels: enhancement, wontfix
