### ISSUE TITLE
Support reading mokuro manga

### ISSUE THREAD

**Issue by PhongTong** [lrorpilla/jidoujisho#152] opened 2023-02-02 07:39 UTC
I found a really large resource of mokuro type pdf.
This is a collection of manga converted to pdf mangas with selectable text by the help of Mokuro2Pdf script.
Really useful for immersion study.
https://mega.nz/folder/WCxngBgT#lxN3b7ihdjMmnHPgzUJYQw
Sadly, I can't find any program to read the pdf file comfortable and support good dictionary like Yomichan..
Therefore, I hope you can consider supporting reading Mokuro in the future. Thank you in advance.

**Comment by lrorpilla** [comment] 2023-02-02 08:20
Hi, this is a duplicate of #114. My plan is to improve dictionary search but this is definitely in consideration for after that.

**Closed by lrorpilla** 2023-02-02 08:20 UTC
