### ISSUE TITLE
Is this a problem of mine or...?

### ISSUE THREAD

**Issue by CupricAdamo** [lrorpilla/jidoujisho#2] opened 2021-02-06 23:06 UTC
Does the app support .mkv videos?
'cuz I've downloaded an anime and tried to open it with the app but doesn't load it.

**Comment by lrorpilla** [comment] 2021-02-07 01:31
Ah, whoops. Mispressed with the issue close.

Please provide more details, like your device make and model, Android version, what video you're playing and whatever else you're loading onto the app.

Occasionally some videos won't play and that prompts me to exit back to the menu and try again, but I've never encountered a local video that refuses to play after attempting again. If you can help provide details that will assist me in reproducing this issue, it would really let me sort this out.

**Comment by CupricAdamo** [comment] 2021-02-07 08:44
My smartphone is a xiaomi redmi 9c. Android 10qp1a, MIUI 12.0.6.
I tried many times to view two different videos of 1gb or more. I can say this videos aren't broken because I can view them with MI video player and VLC.

**Comment by lrorpilla** [comment] 2021-02-07 08:53
How much storage space do you have left remaining on your phone? <b>[Due to the scoped storage changes in Android 11](https://developer.android.com/about/versions/11/privacy/storage),</b> videos have to be cached into temporary storage (as in, they have to be copied by the app into storage to play, thus you will need twice the size of the videos you are playing). Currently, I clear this cache every time the app starts. <b>If your amount of free space is just below the size of the video file you have chosen, the video would be unable to play.</b>

I implemented a change in how files are selected in order to allow Android 11 users to use the app, at the cost of loading time and storage space issues. <b>This is a change that was not necessary in prior versions of the app before 0.3.2, and it is a requirement for the app to work on versions above Android 10.</b>

If this is indeed the issue you are facing, I would just like to express that I am also unhappy with this change and would like to bring back the faster, instant video playback without any storage requirements or workarounds required to let users run the app on Android 11. I will probably implement two versions for users to download so that they can choose between the two options.

In the meantime, I recommend that you use a version below 0.3.2 if you wish to use the app without these storage issues. Please do confirm if this guess is correct, though. It may be a legitimate player issue.

**Comment by CupricAdamo** [comment] 2021-02-07 08:58
13 gb. 51/64

**Comment by lrorpilla** [comment] 2021-02-07 09:03
That does make it a player issue. Could you let me know some details on the file you are playing?

**Comment by CupricAdamo** [comment] 2021-02-07 09:27
It's a .mkv file, 1.59gb, works on vlc and mi video. Now tried to view a 6mb .kjv file, it didn't work. But it worked with .mp4 files.

**Comment by CupricAdamo** [comment] 2021-02-07 09:28
I'll download an older version how you suggested

**Comment by lrorpilla** [comment] 2021-02-07 10:08
The app's video player uses ExoPlayer, [which has a list of supported formats which can be found here](https://exoplayer.dev/supported-formats.html). I have used MKV videos in my testing and found no major issues that prevented me from playing my videos. If you can provide more details in regards to the video you are playing, I may be able to reproduce the issue. 

 If you can, **[please send me a log or a screenshot with information about the video file which you can get via this application or something similar.](https://mediaarea.net/en/MediaInfo)** It is concerning to me that some video files may not work with the application, so please let me know if you can provide more details.

**Comment by CupricAdamo** [comment] 2021-02-07 11:06
How do I send them?

**Comment by lrorpilla** [comment] 2021-02-07 11:08
You may copy paste the entire log here or attach the photos in your comment while you're editing them.

**Comment by CupricAdamo** [comment] 2021-02-07 11:15
![Screenshot_2021-02-07-12-11-52-953_com google android apps docs](https://user-images.githubusercontent.com/67158778/107144841-2257cb80-693e-11eb-9c52-ec9f641957c3.jpg)

**Comment by CupricAdamo** [comment] 2021-02-07 11:15
![Uploading Screenshot_2021-02-07-12-12-14-267_com.google.android.apps.docs.jpg…]()

**Comment by CupricAdamo** [comment] 2021-02-07 11:17
![Uploading Screenshot_2021-02-07-12-12-14-267_com.google.android.apps.docs.jpg…]()

**Comment by CupricAdamo** [comment] 2021-02-07 11:17
![Uploading Screenshot_2021-02-07-12-12-14-267_com.google.android.apps.docs.jpg…]()

**Comment by CupricAdamo** [comment] 2021-02-07 11:19
That was the biggest file i have

**Comment by CupricAdamo** [comment] 2021-02-07 11:20
This is the smallest 
![Screenshot_2021-02-07-12-19-04-909_com google android apps docs](https://user-images.githubusercontent.com/67158778/107144978-dc4f3780-693e-11eb-8bba-1a5c1e3644ee.jpg)

**Comment by CupricAdamo** [comment] 2021-02-07 11:21
Both of them don't work on jidoujisho for me

**Comment by lrorpilla** [comment] 2021-02-07 13:09
Thank you, this is very useful. I'll look into what alternatives I can use for the video player to solve this issue.

**Comment by lrorpilla** [comment] 2021-02-08 11:49
I should be able to support this format in the upcoming release. I will keep this issue open until that version is released.

**Comment by lrorpilla** [comment] 2021-03-04 12:34
Unfortunately, I don't suppose I can migrate the application to VLC in a stable manner so I don't think I can fix this at the moment until significant updates. In the meantime, the app should support anything that ExoPlayer supports on Android -- alternate videos would have to be found otherwise unfortunately.

I think implementing YouTube as is in addition to keeping subtitles working the way they are would have to change otherwise. I'll close this issue but feel free to bring it up should more significant issues arise.

**Comment by lrorpilla** [comment] 2021-04-04 16:50
I am briefly reopening this issue to announce that [I have recently migrated the app to use VLCKit in the 0.6.0 release](https://github.com/lrorpilla/jidoujisho/releases/tag/0.6.0-beta) and that the videos you are having issues with should now be compatible.

If there are any further issues, please let me know. And with that, I am closing this issue.

**Closed by lrorpilla** 2021-04-04 16:50 UTC
Labels: bug, wontfix
