### ISSUE TITLE
Problem reading and editing online Mokuro page 

### ISSUE THREAD

**Issue by RoYou17** [lrorpilla/jidoujisho#241] opened 2023-06-03 19:15 UTC
I had a Mokuro page hosted through DriveToWeb and opened it with Jidoujisho. It actually worked fine at first but then the page turned full white and became unresponsive. 
I tried to delete the html page from the library and add it again but all I got is the white page and "null" in the adress bar. So I tried tapping the bookmark button on the top right and manually add in the title and URL but as you can see the keyboard kept jumping around and I can't type anything.
I also tried deleting cache of the app and tried again but got the same result.
Also note that I can open the URL from my phone web browser just fine. (I can share the URL if you want but I doubt it's anything specific to it. It's just leads to a regular html page made with Mokuro).

https://github.com/lrorpilla/jidoujisho/assets/57872351/dc659951-dddd-4049-969f-22c79623b070

**Comment by lrorpilla** [comment] 2023-06-03 22:23
I'm not sure what you're trying to do -- It looks like the URL you are entering is being parsed improperly. You will have to share it with me if you want me to act on this.

I don't have any details about the URL, and the information you've given isn't enough to reproduce this issue, so I will need some more to work with.

**Comment by RoYou17** [comment] 2023-06-04 01:58
Sorry if I was too vague. Here's the [link](https://burnerks11moonrunescollection.on.drv.tw/Mokuro/Insecure-Herami-Sisters/vol-01.html) and as you can see it works fine from a browser. It was also working fine inside Jidoujisho up until page 75 or so, then it randomly stopped loading and the screen turned to full white (the controls disappeared too). 
When I deleted it from my library and tried to add it again I got the same blank white page and a "null" in the address bar.

Actually... I tried deleting and adding it again but this time it worked! (for some reason.. I haven't changed anything). 
So not really sure what happened, and sorry again if this too random. I guess the only take away here is that 'something' 'sometimes' can cause the app to display a blank 'null' page instead of the proper html page. And as a side bonus bug when that happens, trying to bookmark a 'null' page (0:11 in the video) and trying to edit its details causes the keyboard to jump around.

**Comment by lrorpilla** [comment] 2023-06-04 11:02
As this issue has resolved itself, and I've fixed keyboard problems in [**2.8.0**](https://github.com/lrorpilla/jidoujisho/releases/tag/2.8.0), I'm closing this issue.

**Closed by lrorpilla** 2023-06-04 11:02 UTC
Labels: bug
