### ISSUE TITLE
My entire library of ebooks disappear for the forth time now 

### ISSUE THREAD

**Issue by Katsumi-III** [lrorpilla/jidoujisho#308] opened 2023-10-02 13:14 UTC
Not entirely sure how to reproduce this bug but, from what I can remember given the somewhat rare occurrence throughout, maybe, the three last latest versions (curr. v. 2.8.9, Android 12); It tends to disappear, never during usage or promptly after, but after some time without using jidoujisho. Most recent occurrence of the bug was today, after reading manga and deciding to jump back to my ebooks for today.
Not entirely sure what I should say but, willing to answer questions to get this resolved.

**Comment by Oshibuki** [comment] 2023-10-03 00:56
Did you update or change your  android webview?The data is stored in that

**Comment by lrorpilla** [comment] 2023-10-05 11:08
I understand your frustration but I have to close this as a duplicate of #147.

**Closed by lrorpilla** 2023-10-05 11:08 UTC
