### ISSUE TITLE
Crash when importing JMDict

### ISSUE THREAD

**Issue by mcdmcdmcdmcd** [lrorpilla/jidoujisho#113] opened 2022-09-07 06:32 UTC
Hi, thanks for your work on Yuuna, though I've encountered a problem.

On v2.0, the app crashed when I tried to import any versions of JMDict, while other dictionaries works fine. It wasn't a problem on v1.1.12, only on the newest release. I've also included a screencast below.

Edit: Seems like the app also crashed when I'm trying to import any dictionary with large entries, though v1.1.12 imports without any issue.

These JMDICTs I got from [TheMoeWay's Resources page](https://learnjapanese.moe/resources/#yomichan).

Additional info:
Device: _Kindle Fire HD8 Plus (10th Gen)_, with 3GB of RAM.
Android version: 9
Jidoujisho version: _jidoujisho_yuuna_2_0_0-armeabi-v7a_hotfix1_

https://user-images.githubusercontent.com/48660041/188803227-ff39fd55-9cfa-423b-89ec-793c2f09377c.mp4

**Comment by lrorpilla** [comment] 2022-09-07 08:51
Hi, I'll have a look and see what's going on. For now, the JMdict you can download from the Yomichan site should work fine.

**Comment by lrorpilla** [comment] 2022-09-07 08:59
The JMdict from shoui's collection seemed to import fine after I renamed the file to something else without special characters, but failed without.

How much free space do you have on the tablet? The database demands a lot of storage space for indexing

**Comment by mcdmcdmcdmcd** [comment] 2022-09-07 11:13
I have documented what I've done based on your suggestions:
- Tried out the JMDICT from Yomichan's site. Crash.
- Renaming the .zip file to both with/without special characters. Crash.
- Double-check the storage, there are >5GB of free space on both Internal and SD Card.
![Screenshot_2022-07_06-05](https://user-images.githubusercontent.com/48660041/188863570-d7bb2f2e-ebbd-4771-b25d-62874edb7cb8.png)
- Quit all running apps except Jidoujisho Yuuna to see if it's a RAM issue. Still crash at importing.
- I've tried importing using other dictionaries, mostly crash if they has a lot of entries.

And all the while v1.1.12 still imports fine without a hitch.

**Comment by lrorpilla** [comment] 2022-09-07 11:44
2.0.1 is out, though I doubt it would make a difference. Chisa and Yuuna use entirely different database solutions, so really I can't track the difference between the two because what goes on with the two dictionary import operations is completely different.

The current build I am using for the database (Isar) is not the most updated, and there have been massive improvements to put operations since, but I have to wait till they go stable and I can migrate.

I'll investigate if it is probably something else. What would be really useful, though it is much to ask, if you can somehow get the logs for the crash through Android Debug Bridge.

**Comment by mcdmcdmcdmcd** [comment] 2022-09-07 12:49
I've included the logs from running the two commands `adb logcat -b crash`, and `adb logcat` where I attempted to recreate the crash.
[adb logcat -b crash 202209070733.txt](https://github.com/lrorpilla/jidoujisho/files/9506233/adb.logcat.-b.crash.202209070733.txt)
[logcat 202209070736.txt](https://github.com/lrorpilla/jidoujisho/files/9506231/logcat.202209070736.txt)

As you said, the problem is still there on v2.0.1. At least for the time being I can still rely on the Kenkyusha/Shinwaei dict(which imported fine) until the cause of the import bug is identified. Apart from that, Yuuna has been a solid update, with no other issues so far.

**Comment by Specki123** [comment] 2022-09-07 20:03
I have the same problem but i can't even import Shinwaei

**Comment by lrorpilla** [comment] 2022-09-21 11:49
To address this issue, I have upgraded the backing database solution and improved the performance of the dictionary search speed. This is a preview version, so your mileage may vary.

You will need to wipe your data or uninstall the app first in order to use this version.

The preview can be found **[here](Preview for jidoujisho 2.1.0
https://drive.google.com/drive/folders/1ZZwcnOTt_V-7e7LtLsxLuFmlv1crTCBo).**

**Comment by mcdmcdmcdmcd** [comment] 2022-09-22 08:53
> To address this issue, I have upgraded the backing database solution and improved the performance of the dictionary search speed. This is a preview version, so your mileage may vary.
> 
> You will need to wipe your data or uninstall the app first in order to use this version.
> 
> The preview can be found **[here](https://drive.google.com/drive/folders/1ZZwcnOTt_V-7e7LtLsxLuFmlv1crTCBo).**

Hi again, thanks for still sticking with this issue.

I've done a clean install of v2.1.0. Unfortunately, the crash to home screen is still there when I'm trying to import dictionaries with large entries, no difference from v2.0.1.

**Comment by lrorpilla** [comment] 2022-09-22 08:56
If small dictionaries import fine, maybe it's a matter of all the work having to be done at once. Can you try and see if importing many small dictionaries causes an issue?

If you can import a lot of small dictionaries with around the same amount as one big dictionary that works, that tells me that the issue is the size of the work to be done and maybe it'll work out if I split up the import into many small steps.

**Comment by mcdmcdmcdmcd** [comment] 2022-09-22 10:49
I'm not sure what you meant, but I did try to import 5 dictionaries with a small number of entries all at once: the import process went through fine without issue. By the way, it was the same with v2.0.1.

After that, I tried importing a 300k entries frequency list (around the 2 min mark). Sure enough, Jidoujisho crashed, even though the .zip was less than 3MB.

Here's the screencast:
https://user-images.githubusercontent.com/48660041/191710870-9d76ee99-0943-4409-8318-87a353c842ff.mp4

**Comment by lrorpilla** [comment] 2022-09-22 10:55
What I meant is that if I stage the import of a big dictionary into maybe ten small steps, maybe the import will work.

If you can say, import 50K entries ten times, but not 500K dictionaries all at once, then that tells me maybe something I can do is divide the work and perform it ten times, instead of stressing your device to perform something all at once.

So, if your device is able to play well with say, 300K entries imported in small amounts, then I think we have a potential solution.

**Comment by mcdmcdmcdmcd** [comment] 2022-09-22 14:39
> @mcdmcdmcdmcd I'm going to share a build that splits the database imports into 10K objects maximum at a time, multiple times. Can you please see if it performs any differently on your device?
> 
> I've updated the preview builds in the same link **[here](https://drive.google.com/drive/folders/1ZZwcnOTt_V-7e7LtLsxLuFmlv1crTCBo).**

Tested your new v2.1.0 build: the import speed was noticeably slower, but I am now able to get all dicts to work, including ones with large number of entries. Seems like this is the solution going forward!

![Screenshot_2022-22_09-29](https://user-images.githubusercontent.com/48660041/191775353-fdad5117-c17a-4acd-a15f-a333340a3d89.png)

So in the end, is it a device-specific bug, or it is related to Yuuna's new database solution?

Cheers!

**Comment by lrorpilla** [comment] 2023-01-09 16:51
This was resolved in **[2.2](https://github.com/lrorpilla/jidoujisho/releases/tag/2.2)**:
- A new option for slow import has been added for users that experience crashing on older devices so as to not penalize users with faster devices.

If you still have import-related issues, feel free to re-open.

**Closed by lrorpilla** 2023-01-09 16:51 UTC
Labels: bug
