### ISSUE TITLE
Cards NOT created in Samsung Galaxy Tab 7

### ISSUE THREAD

**Issue by r-ichi** [lrorpilla/jidoujisho#138] opened 2023-01-01 07:14 UTC
when trying to "create a card from context" 
playing an MKV file, 
loaded with external subtitles in SRT format

the card generator panel has the audio, the screenshot, the sentence and everything.

still, when pressing "create card" and receiving the message "card added to X-deck", such card simply does not get exported to the respective Anki deck.

device:
CPU architecture : ARMv8-A
Instruction Sets   : arm64-v8a
OS version         : Tiramisu (13)
 SDK                  : 33
Java VM             : ART 2.1.0 

Could it be something with the permissions of something Samsung-related? 
(all possible permissions have been granted for both Anki and Jidoujisho in the "Apps" section of the device settings)

is there any way to fix it myself?

This project is amazing, probably the the best tool for self-learning out there.
It really makes being alive in this era worth it.

Cheers, lrorpilla. 
You're awesome.

**Comment by lrorpilla** [comment] 2023-01-01 08:09
I reckon it's related to a permissions issue related to adding the image and audio file, which fails due to where those files are placed before being passed to AnkiDroid to be added to the media collection.

I had someone report something similar and my suspicion is probably correct if you try exporting a card without an audio and image and it happens to work.

**Comment by r-ichi** [comment] 2023-01-01 14:34
damn, is that related to how the device is natively configured by the manufacturer? or is there a way to override that?

Thank you :)

**Comment by lrorpilla** [comment] 2023-01-02 06:14
This will require a new version, I will probably try to get my hands on a test device that has this issue.

**Comment by r-ichi** [comment] 2023-01-03 21:22
small update to the issue after checking the suggestion,
no cards (regardless of the type/content/method of construction) get exported to Anki in this device
even without audio and no image.

**Comment by lrorpilla** [comment] 2023-01-03 22:39
What does your export profile look like? Could you take a screenshot? You can find yours by going to the main menu and selecting Export profiles and selecting Edit on your profile.

**Comment by r-ichi** [comment] 2023-01-04 06:50
The profile seems to simple the standard one. 
The screenshot here:

![Screenshot_20230104_014621](https://user-images.githubusercontent.com/36776421/210499564-11d32e9b-32e5-43b3-9c32-6afc6f6ddfa3.jpg)

**Comment by lrorpilla** [comment] 2023-01-04 06:52
Hi, I will need to see profile being edited. Select the three dots option on the upper right and click on Edit and you should screenshot that screen instead.

**Comment by r-ichi** [comment] 2023-01-04 06:58
All the fields have are on "Empty" ...
Could the solution be that simple? :/

**Comment by lrorpilla** [comment] 2023-01-04 07:11
Yeah, in some versions the fields are possibly not set so if you put something in there, you can probably export properly. I'm going to add a message that tells you that you can't export with a completely empty profile at some point. Let me know if it works after you've set the fields.

**Comment by r-ichi** [comment] 2023-01-04 07:19
This is still better than having no output at all, and a new version that handles this issue will probably take a good amount of your time. 
In the meantime  I'll try to experiment with some profile configs and see if it's possible to get the images working and report the results here if there's any success.

Thank you so much for your support and for creating this great app.

**Comment by lrorpilla** [comment] 2023-01-04 08:24
I have a potential fix for this issue but it will require testing on your device. Can you please try [this version](https://drive.google.com/file/d/135TT9xFnrjbFThoPJ-22QdFDBdN0uYxQ/view?usp=share_link)? You might need to uninstall to try and install the version.

**Comment by lrorpilla** [comment] 2023-01-04 09:38
I've updated the version above, you can download it from the same link but if you happened to download it prior, I've fixed an issue which causes a white screen in the player.

**Comment by r-ichi** [comment] 2023-01-05 01:50
Uninstalled and rebooted the device,
Tried to mine a card from an mkv source as described above (with the default profile and no c

**Comment by lrorpilla** [comment] 2023-01-05 02:10
Looks like this issue is reported by users who have Motorola and Samsung devices so far, and I'm sure others are affected too. It's almost probably an issue related to scoped storage permissions. I will investigate further but the biggest difficulty I have is the lack of a device to reproduce and test with (I have a Pixel device).

**Comment by r-ichi** [comment] 2023-01-05 02:18
Curiously, in my MotoG8, Chiisa is slow but works and exports from video contexts are possible. Idk about Yunna, though. If there's any way to help you with testing or somehow making this Samsung device remotely available for you, count on me.

**Comment by lrorpilla** [comment] 2023-01-05 02:42
Could you please test Yuuna on your moto and see if you get the same behaviour, and Chisa on your Samsung? It would help me get an idea of what's going on and whether I can reuse Chisa code as a fallback.

Thanks for being readily eager to help me debug.

**Comment by r-ichi** [comment] 2023-01-05 03:14
The perspective of immersion makes absolute sense, unfortunately in the beginning stages it takes a long time to "intuitively" grasp what's going on and translations (e.g. subtitles on a known language) help a lot, but at the same time limit the learning process and might even make the learner reliant on them. It takes some time before you notice that is "better" not to have any translations at all. 

There's something about this transition process where you go back and forth (translated_subs, jap_only_subs) and the app being intended mainly for monolingual purposes is probably the best course of action. I personally intend to use it for mining only things that I can't understand, or those that one day make sense, but the next day I have no idea what it meant... weird transition phenomenon.


I'll try Yuuna on the Moto, the performance sucks so it might take a while.

About Chiisa on the tablet, I can give it a try right now, BUT I do remember trying it before in the Samsung tab and failing to export too, but is there any specific version to try that experiment with?

**Comment by r-ichi** [comment] 2023-01-05 03:47
MotoG8 Chiisa 1.1.2    
adequately creates cards from a local video source with subtitles. [ card id properly found in Anki ]
When sourcing from youtube, it fails to generate/crop the audio (even before the export) [ card is found in Anki with no audio]

MotoG8 Yuuna 2.1.0
from local media: generates card template properly, but again fails to export it [ nowhere to be found in Anki ]

**Comment by lrorpilla** [comment] 2023-01-05 05:12
I recommend editing your card type in Anki to

- Rename your Audio to Term Audio 
- Add a Sentence Audio field at the very last after the last field

This should bring your card type to be exactly the same as the new default card type added by the app (the default number of fields were changed post-2.0). Try changing the card type in Anki. Once you reinstall the app, you will notice that the Standard export profile no longer has empty fields by default.

It should be as such:
![Screenshot_20230105-151102](https://user-images.githubusercontent.com/11363922/210706408-247be020-6fa1-4380-800e-fca3acd5af06.png)

**Comment by lrorpilla** [comment] 2023-01-05 05:15
Double-check that your Anki template for "jidoujisho Yuuna" is as such:

Front
```
<div id="word">{{Term}}</div><hr>
```

Back
```
<div id="word">{{Term}}</div><hr><p id="sentence">{{Sentence}}</p><br>{{#Term Audio}}[sound:{{Term Audio}}]{{/Term Audio}}{{#Sentence Audio}}<br>[sound:{{Sentence Audio}}]{{/Sentence Audio}}{{#Image}}<div class="image"><img src="{{Image}}"></div>{{/Image}}{{#Pitch Accent}}<br>{{Pitch Accent}}<br>{{/Pitch Accent}}<br><h2 id="word">{{furigana:Furigana}}</h2><br>{{#Meaning}}<p><small id="meaning">{{Meaning}}</p </small><br>{{/Meaning}}{{#Expanded Meaning}}<p><small id="meaning">{{Expanded Meaning}}</small></p>{{/Expanded Meaning}}<br>
{{#Collapsed Meaning}}<details><summary></summary>
<p><small id="meaning">{{Collapsed Meaning}}</small></p>
</details>{{/Collapsed Meaning}}
```

CSS
```
p {
    margin: 0px
}

h2 {
    margin: 0px
}

small {
    margin: 0px
}

.card {
  font-family: arial;
  font-size: 17px;
  text-align: center;
  color: black;
  background-color: white;
  white-space: pre-line;
}

#sentence {
    font-size: 30px
}

.context.night_mode {
    text-decoration: none;
    color: red;
}
.context {
    text-decoration: none;
    color: red;
}

.image img {
  position: static;
  height: auto;
  width: auto;
  max-height: 150px;
}
.pitch{
  border-top: solid red 2px;
  padding-top: 1px;
}

.pitch_end{
  border-color: red;
  border-right: solid red 2px;
  border-top: solid red 2px;  
  line-height: 1px;
  margin-right: 1px;
  padding-right: 1px;
  padding-top:1px;
}
```

**Comment by lrorpilla** [comment] 2023-01-05 05:16
I know that's a lot, but I just want to make sure it's not a template issue before I investigate more.

**Comment by r-ichi** [comment] 2023-01-05 06:40
I'm not an expert on Anki, by any means, and know little about configuring the fields in Anki... or in Jidoujisho... 
Sorry, I'm trying to do this to the best of my current capabilities.

I'm trying to use windows to access the Anki collection and create a new template ("Note Type") 

![image](https://user-images.githubusercontent.com/36776421/210717358-3ced0525-ce26-44a3-9696-01415897238e.png)


When pasting the pieces of html code you provided, the results are:
-it is not possible to save the template due to a mismatch somewhere in the code


![image](https://user-images.githubusercontent.com/36776421/210716944-1d6672d4-f799-4b01-993a-8211a4e61627.png)

![image](https://user-images.githubusercontent.com/36776421/210717012-ce15b522-b671-434c-9455-15fdb840443b.png)

![image](https://user-images.githubusercontent.com/36776421/210717084-f512ee7a-0166-41ad-a5c7-26689910ef94.png)


I tried manipulating some of the brackets of {{Term}} changing it to {Term}, but no success.

**Comment by lrorpilla** [comment] 2023-01-05 06:42
Given that you only have 3 notes under jidoujisho Yuuna, you can just delete the card type under AnkiDroid.

Then, you can try running 2.2.0 and have it re-add a new jidoujisho Yuuna default card type. That will be easier than everything I just said above.

**Comment by r-ichi** [comment] 2023-01-06 02:57
It finally worked!

deleting all those notes and and letting Yuuna create the "jidoujisho Yuuna" profile automatically after the installation.
A new "exporting profile" had to be created for this, with all the fields set like you mentioned and the last option ( 'Wrap Image/Audio with Tags) set to 'off/deactivated'

Now cards created from videos are properly found in Anki
If there's any need for screenshots or more details of the process let me know.

by the way, is there a way to create a profile that generates reverse cards too? 
a way to expand the audio length that's mined from a video by a few seconds? (a few seconds earlier and/or few seconds later)
and is there a way to get this 2.2.0 version for a MotoG8 ? unfortunately Yuuna in this device crashes when trying to import dictionaries.


Thank you for all your patience.
Regads

**Comment by lrorpilla** [comment] 2023-01-06 04:09
Hi, @r-ichi, I've officially released 2.1 (downed the version as I realize there hasn't been an official one), could you please try and see if that imports better on your G8?

**Comment by lrorpilla** [comment] 2023-01-09 16:30
@r-ichi, you can use the Audio Allowance option to adjust the allowance bi-directionally if you want just a bit more longer audio. As for reverse cards, you will need to make your own export profile. I'd be happy to hear what you think of the 2.2 performance gains.

I'm going to close this issue in a couple days, but you are welcome to follow up and make a new one regarding that dictionary if I don't get around to testing it.

**Closed by lrorpilla** 2023-01-09 16:30 UTC

**Comment by r-ichi** [comment] 2023-01-10 06:10
perfect!

one last thing, I found out that if the "sentence" field is left to 'empty', that causes cards not to be generated (under any condition it seems)

hopefully that detail will also help you on the continuous development of your project
cheers!

**Comment by lrorpilla** [comment] 2023-01-10 06:18
Do you mean if the export profile is set to Empty? I can't replicate this issue, I've set my export profile to Empty and cards with only Term set on them export just fine.

If you're willing to send some examples and screenshots dealing with this situation, I would be happy for you to report this as a new issue.

**Comment by r-ichi** [comment] 2023-01-11 03:58
Sure. It might still be an issue of this specific type of device and not apply to other devices (not galaxy tab 7),  but I'll try to replicate it and open an issue

**Comment by r-ichi** [comment] 2023-01-11 19:43
Sure. It might still be a problem for this specific type of device (galaxy tab), but I can try to replicate it and open an issue for it with the videos/screenshots

how do you access the "audio allowance" option?

thanks!

**Comment by lrorpilla** [comment] 2023-01-11 22:43
Should be under the audio/subtitles menu (the button before the bottom-right button in the player
