### ISSUE TITLE
Forvo audio preview stops current playing audio

### ISSUE THREAD

**Issue by Feripe-a** [lrorpilla/jidoujisho#85] opened 2022-02-17 19:30 UTC
I've found the following bug while listening to a podcast and making flashcards:

https://user-images.githubusercontent.com/84395172/154556227-e48d82ac-fd8d-4475-bdc9-1c1671483ba1.mp4

**Comment by lrorpilla** [comment] 2022-02-18 04:02
At the time being this is intended behavior.

Maybe I can find a way to make the backing audio player in the app not interrupt other apps (surely there is a configuration), I'll note this down.

**Comment by lrorpilla** [comment] 2022-09-07 09:22
Closing this as **[2.0](https://github.com/lrorpilla/jidoujisho/releases/tag/2.0.0)** has been released. See the relevant lines in release notes.

- Playing audio in the app will now duck the audio of current playing media instead of stop media.

**Closed by lrorpilla** 2022-09-07 09:22 UTC
