### ISSUE TITLE
Dictionary not showing meanings

### ISSUE THREAD

**Issue by Whitesttax** [lrorpilla/jidoujisho#289] opened 2023-08-04 17:51 UTC
I'm new to the app, not sure what's going on but I get this very frequent like the image below.
If you use yomichan on 図々しい you can see that JMdict Extra has lots of meanings, not sure why it doesn't show on jidoujisho. 
I don't remember if it only happens to JMdict Extra, will try to take a look in the coming days. 
<img width="192" alt="image" src="https://github.com/lrorpilla/jidoujisho/assets/20992483/d90789eb-9e37-47d6-8b09-a45f1c0d81e6">
edit: here's another example, exactly like the one above: この期に及んで

**Comment by lrorpilla** [comment] 2023-08-04 22:12
Duplicate of #174.

**Closed by lrorpilla** 2023-08-04 22:12 UTC
