### ISSUE TITLE
Audio interruptions after pause/unpause are still happening on version 2.7.2

### ISSUE THREAD

**Issue by DiamondScythe** [lrorpilla/jidoujisho#233] opened 2023-05-28 04:11 UTC
Apparently this was fixed in an earlier update, but the bug is still happening for me. I can reliably reproduce the bug by pausing to view the dictionary entries for an extended period of time.

Video of me reproducing the bug (see 0:30 onwards)

https://youtu.be/-JCC9hESfp8

**Comment by lrorpilla** [comment] 2023-05-28 04:26
This is a duplicate of #225, and a linked issue of #231 so I'm going to have to close this issue and request that discussion about this issue is moved in #231 instead.

**Closed by lrorpilla** 2023-05-28 04:26 UTC
