### ISSUE TITLE
Can't Access Local Storage

### ISSUE THREAD

**Issue by T1CkShot** [lrorpilla/jidoujisho#66] opened 2021-12-16 11:22 UTC
My phone is Techno IN1 pro. Android 8.1.0 . When I try to import dictionary using yomichan term bank after tapping import nothing happens and if I tap the local storage bar for the player keyboard pops up but nothing happens. For the button beside the bar same thing happens as the import button. I've already tried removing permission and giving it again from settings and re installing the app as well

**Comment by lrorpilla** [comment] 2021-12-16 12:08
Please provide more details about when this issue started, and give the version of the app you're trying to use, and whether  and which older versions worked

**Comment by T1CkShot** [comment] 2021-12-16 12:13
When I first updated to the 1.0 version I had this issue. I thought it was device but after updating to the next hotfix it worked. After 1.1 its not working again i've tried all of the 1.1 versions but cant access local storage.

**Comment by lrorpilla** [comment] 2021-12-16 12:35
I have identified an error in Crashlytics relating to the file picker. While I am able to reproduce an error that pops up when opening the file picker, I am unable to reproduce the behavior of the file picker not showing.

For now, I am releasing a preliminary APK, let me know how you do with it, it's an armeabi APK file.

You can get it here: https://drive.google.com/drive/folders/185s7q043r4OyVQbxM9fq3Vfln4nWKslL?usp=sharing

I am not sure if this resolves the issue, so please let me know how you do with it. If all else fails, then I will still get the stack trace from the error that you get in Crashlytics. As this version is 1.1.6, I'll be able to filter out any issues you have from the rest.

**Comment by T1CkShot** [comment] 2021-12-16 13:21
I've installed the provided apk. Unfortunately after installing it I'm unable to open the app it crashes when I try to open it

**Comment by lrorpilla** [comment] 2021-12-16 13:30
Apologies. That's on me, screwed up the build step.
Will notify you when I've reuploaded it, will be on the same folder

**Comment by lrorpilla** [comment] 2021-12-16 13:33
https://drive.google.com/file/d/1N-785moZZ2gIAYxkOg_dvmdmtfKzz3Dz/view?usp=sharing

**Comment by T1CkShot** [comment] 2021-12-16 15:52
I've installed the new one. Everything works fine now the file picker is showing. I've tried importing dictionary, playing video, loading ebook and everything worked. Thank you and sorry for the trouble.

**Comment by lrorpilla** [comment] 2021-12-16 22:03
I'm glad to hear that. Fixed in [**1.1.6**](https://github.com/lrorpilla/jidoujisho/releases/tag/1.1):
- 🔨 **Fixed an issue where some users were unable to open the file picker** due to a null-related error.

If there are any follow-up issues, you're welcome to re-open.

**Closed by lrorpilla** 2021-12-16 22:03 UTC

**Comment by T1CkShot** [comment] 2022-01-05 22:00
The same issue is occurring once again in 1.1.10 this time.

**Comment by lrorpilla** [comment] 2022-01-06 02:20
Nothing related to file picking has changed in commits from 1.06 to 1.10 since I applied the fix, I could use a video to see what's going on, but honestly I don't think it would be as useful as hooking your phone onto adb on a PC and then sending me the error logs. Crashlytics isn't returning anything useful to me so I'll probably add a way for you to view the logs in an upcoming version

**Comment by T1CkShot** [comment] 2022-01-06 11:48
Sorry. It was my device I guess. I had forgotten my phone had a broken sd card in it. after removing the sd card and reinstalling Jidoujisho file picker is working once again.
