### ISSUE TITLE
All fonts in the application are Chinese except in ttu

### ISSUE THREAD

**Issue by dstntwrldstgthr** [lrorpilla/jidoujisho#125] opened 2022-09-18 06:27 UTC
I set my Android language to Japanese and removed all other languages.

**Comment by lrorpilla** [comment] 2022-09-18 07:23
Hi, I would appreciate examples of words with screenshots showing the problem, with comparison images with what you expect.

Attached is an image of 直す showing as it should in Japanese.

**Comment by lrorpilla** [comment] 2022-09-18 07:24
![Uploading Screenshot_20220918-172313.png…]()

**Comment by lrorpilla** [comment] 2022-09-18 07:24
![Screenshot_20220918-172313](https://user-images.githubusercontent.com/11363922/190890696-5642a695-539d-4927-a141-465c9e916827.png)

**Comment by lrorpilla** [comment] 2022-09-18 07:32
The app is actually set up to forcibly show in a Japanese font and locale with no need for a user to tinker with their language settings. Supposedly, it should without any changes, always show in a Japanese font/locale.

If you can show any counterexamples that contradict this behaviour, I would be happy to investigate the problem.

**Comment by dstntwrldstgthr** [comment] 2022-09-18 07:36
FYI this is on Galaxy S8 Android 9
![Screenshot](https://user-images.githubusercontent.com/113819144/190891071-0f3510ea-8ff9-4708-85a4-a8c86d90eb2c.jpg)
![Screenshot2](https://user-images.githubusercontent.com/113819144/190891074-502e20f5-ee1d-4f03-830a-de0e6bd293a1.jpg)

**Comment by lrorpilla** [comment] 2022-09-18 08:00
@dstntwrldstgthr, I'm going to upload a fix shortly and please let me know if the problem is fixed; I will release it as a new bug fix if it works.

**Comment by lrorpilla** [comment] 2022-09-18 08:05
Fix uploaded [**here**](https://drive.google.com/file/d/1Kwe6l2jR5iEnvqqCqukecsy_Y41S4XYj/view?usp=sharing).

**Comment by dstntwrldstgthr** [comment] 2022-09-18 08:14
Sorry, the issue remains.

**Comment by lrorpilla** [comment] 2022-09-18 08:21
I want to further look into this but really it's just difficult to replicate. Even after deleting and forcing my locale to be Chinese and removing all other locales on my phone, I can't replicate this behaviour.

I have a tester that also can't replicate this. If any other user can report this issue, I can give it further investigation. In the meantime, I can probably build you a special version that will forcibly load a font that can't fallback to Chinese.

**Comment by dstntwrldstgthr** [comment] 2022-09-18 08:35
I would greatly appreciate the special version!

**Comment by lrorpilla** [comment] 2022-09-18 08:38
Hi, @dstntwrldstgthr. You can find it [here](https://drive.google.com/file/d/15XMt2MiQIub9ckNKLj-3-rWCWXBs42s2/view?usp=sharing).

Note that at the start, you will find that nothing has changed but after a while, the app will finish downloading a font from Google Fonts and load that all the time afterwards. I picked a font that does not have Chinese support. Let me know how you go afterwards.

**Comment by dstntwrldstgthr** [comment] 2022-09-18 08:48
It appears the issue is fixed everywhere except on subtitles. Is there a way to force the same font to the subtitles?

**Comment by lrorpilla** [comment] 2022-09-18 08:51
Hi, @dstntwrldstgthr.
The subtitles have a separate option under Subtitle Timing and Appearance in the video options. You can set the font name to "Sawarabi Mincho" or "Sawarabi Gothic".

The font that I've assigned to everything else is called "M PLUS Rounded 1c". You can copy paste any of these font names without quotes to the font name box in the options to change the subtitle font.

I might make an option to allow you to change these settings app-wide from the main menu.

**Comment by lrorpilla** [comment] 2022-09-18 08:55
Sorry for the trouble, I know it might be difficult to access and edit the font name option. You can copy the font name I specified above and paste it then make sure to save the option (not just set it).

**Comment by dstntwrldstgthr** [comment] 2022-09-18 08:59
Got it, all set now. Thank you very much!

**Comment by lrorpilla** [comment] 2022-09-18 09:01
Glad to hear it. I'll definitely add a way to customise the font across the entire app in a future version.

**Closed by lrorpilla** 2022-09-18 09:01 UTC
