### ISSUE TITLE
Subtitle remains visible until the next one is displayed

### ISSUE THREAD

**Issue by sp3ctum** [lrorpilla/jidoujisho#14] opened 2021-04-24 17:42 UTC
In some cases, a subtitle line lasts for a couple of seconds, say, and then it should end according to the transcript, followed by a break of some time before the next subtitle line.

So
- sub1 should be shown for 5s
- there should be no subtitle visible for 5s
- a new subtitle line should be shown

In my case the second step is skipped, meaning the first line is not hidden.

**Comment by sp3ctum** [comment] 2021-04-24 17:43
Just verified this doesn't make exporting that sub line any longer (audio wise) than what the transcript says. So maybe this is not that bad.

**Comment by lrorpilla** [comment] 2021-04-24 18:47
I consider this a feature, not a bug. Yes, there are instances where there may be something like an opening playing and the subtitle will be left playing, but this solves many nuances with subtitles being too hard to catch or the very slightest bits of text too hard to rewind for.

**Comment by lrorpilla** [comment] 2021-04-24 21:55
Found an elegant solution for this that should hide the subtitle while keeping it as the current context (if the subtitle end time is past, the widget hides -- internally, the previous subtitle is still kept so export and seek backs should still be the subtitle, just hidden from view). Should be included in the next version.

**Comment by lrorpilla** [comment] 2021-04-24 23:14
I have implemented this feature in [0.13.3](https://github.com/lrorpilla/jidoujisho/releases/tag/0.13.3-beta).

See the relevant line in the release notes:
* **Subtitle widget will now be hidden** from view if they are not within **a 100ms range** of the last subtitle viewed

With that, I am closing this issue.

**Closed by lrorpilla** 2021-04-24 23:14 UTC
Labels: bug, enhancement
